// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Models;

namespace webapi.Migrations
{
    [DbContext(typeof(BlocksContext))]
    [Migration("20210111171811_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("webapi.Models.Ball", b =>
                {
                    b.Property<string>("User")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User");

                    b.Property<float>("Speed")
                        .HasColumnType("real")
                        .HasColumnName("Speed");

                    b.HasKey("User");

                    b.ToTable("Balls");
                });

            modelBuilder.Entity("webapi.Models.Slider", b =>
                {
                    b.Property<string>("User")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.HasKey("User");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Username");

                    b.Property<int>("HS")
                        .HasColumnType("int")
                        .HasColumnName("HighScore");

                    b.Property<string>("LoptaUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("SliderUser")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.HasIndex("LoptaUser");

                    b.HasIndex("SliderUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.HasOne("webapi.Models.Ball", "Lopta")
                        .WithMany()
                        .HasForeignKey("LoptaUser");

                    b.HasOne("webapi.Models.Slider", "Slider")
                        .WithMany()
                        .HasForeignKey("SliderUser");

                    b.Navigation("Lopta");

                    b.Navigation("Slider");
                });
#pragma warning restore 612, 618
        }
    }
}
